envVarGroups:
  - name: opportunity-hub-shared
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: 0
services:
  - type: web
    name: opportunity-hub
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn global_opportunity_agent.wsgi:application
    envVars:
      - fromGroup: opportunity-hub-shared
  - type: worker
    name: opportunity-hub-worker
    env: python
    buildCommand: ./build.sh
    startCommand: celery -A global_opportunity_agent worker --loglevel=INFO
    envVars:
      - fromGroup: opportunity-hub-shared
  - type: worker
    name: opportunity-hub-beat
    env: python
    buildCommand: ./build.sh
    startCommand: celery -A global_opportunity_agent beat --loglevel=INFO
    envVars:
      - fromGroup: opportunity-hub-shared
