# Generated by Django 6.1.1 on 2026-10-06 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('opportunity_type', models.CharField(choices=[('job', 'Job'), ('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('grant', 'Grant'), ('training', 'Training Program'), ('study', 'Study Opportunity'), ('exchange', 'Exchange Program'), ('volunteer', 'Volunteer Opportunity'), ('research', 'Research Opportunity'), ('competition', 'Competition'), ('other', 'Other')], default='job', max_length=40)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('remote_worldwide', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('education_requirements', models.TextField(blank=True)),
                ('experience_requirements', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('salary_stipend', models.CharField(blank=True, max_length=255)),
                ('benefits', models.TextField(blank=True)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('telegram_contact', models.CharField(blank=True, max_length=120)),
                ('physical_address', models.TextField(blank=True)),
                ('organization_website', models.URLField(blank=True)),
                ('raw_source_content', models.TextField(blank=True)),
                ('dedupe_hash', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adapter_type', models.CharField(default='generic', max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('matching', 'Matching'), ('prepared', 'Prepared'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('result_url', models.URLField(blank=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_history', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunity_agent.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('matching', 'Matching'), ('prepared', 'Prepared'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_log', to='opportunity_agent.application')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('rss', 'RSS Feed'), ('telegram', 'Telegram Channel'), ('api', 'API'), ('university', 'University'), ('ngo', 'NGO'), ('government', 'Government'), ('company', 'Company Career Page'), ('other', 'Other')], default='website', max_length=40)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('opportunity_types', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('trust_score', models.FloatField(default=0.0)),
                ('scan_frequency', models.CharField(default='daily', max_length=80)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('last_successful_scan', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('auto_discovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'status'], name='opportunity_enabled_c940d0_idx'), models.Index(fields=['source_type'], name='opportunity_source__563763_idx')],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunity_agent.source'),
        ),
        migrations.CreateModel(
            name='TelegramDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('source', 'Source Channel'), ('destination', 'Destination Group'), ('admin', 'Admin Destination')], default='destination', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('chat_id', 'type')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('current_country', models.CharField(blank=True, max_length=120)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('worldwide_preference', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.TextField(blank=True)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('work_experience', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('other_links', models.JSONField(blank=True, default=list)),
                ('preferred_opportunity_types', models.JSONField(blank=True, default=list)),
                ('preferred_work_modes', models.JSONField(blank=True, default=list)),
                ('visa_sponsorship_preference', models.BooleanField(default=False)),
                ('salary_stipend_preference', models.CharField(blank=True, max_length=255)),
                ('minimum_ai_match_score', models.IntegerField(default=75)),
                ('auto_apply', models.BooleanField(default=False)),
                ('daily_application_limit', models.IntegerField(default=5)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='opportunity_action_07f7aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='opportunity_status_5db277_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='opportunity_user_id_17d895_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_application_per_user_opportunity'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['country', 'status'], name='opportunity_country_0145f8_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline'], name='opportunity_deadlin_f6300a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization'], name='opportunity_organiz_5849ce_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['current_country'], name='opportunity_current_9ff954_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['auto_apply'], name='opportunity_auto_ap_86a6e2_idx'),
        ),
    ]
