# Generated by Django 5.2.18 on 2026-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0004_email_mailbox_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20),
        ),
    ]
