# Generated by Django 5.2.18 on 2026-10-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0005_opportunity_work_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('retry_application', 'Can retry failed applications'), ('review_application', 'Can review pending applications')]},
        ),
        migrations.AlterModelOptions(
            name='provideradapter',
            options={'permissions': [('manage_automation', 'Can manage automation configuration')]},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'permissions': [('scan_sources', 'Can scan opportunity sources')]},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'permissions': [('manage_ai_settings', 'Can manage AI configuration'), ('manage_security_settings', 'Can manage security settings')]},
        ),
        migrations.AlterModelOptions(
            name='telegramdestination',
            options={'permissions': [('manage_telegram', 'Can manage Telegram configuration')]},
        ),
    ]
