# Generated by Django 5.2.18 on 2026-10-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0006_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='scan_frequency',
            field=models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('every_6_hours', 'Every 6 hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=24),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('website', 'Website'), ('job_site', 'Job Website'), ('scholarship_site', 'Scholarship Website'), ('university', 'University'), ('ngo', 'NGO'), ('government', 'Government'), ('international_org', 'International Organization'), ('company', 'Company Career Page'), ('fellowship_portal', 'Fellowship Portal'), ('grant_portal', 'Grant Portal'), ('rss', 'RSS Feed'), ('telegram', 'Public Telegram Channel/Group'), ('api', 'Public API'), ('discovered', 'Discovered Public Source'), ('other', 'Other')], default='website', max_length=40),
        ),
    ]
