# Generated by Django 5.2.18 on 2026-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0007_alter_source_scan_frequency_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('scanning', 'Scanning'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
