# Generated by Django 5.2.18 on 2026-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0008_alter_source_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('job', 'Job'), ('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('grant', 'Grant'), ('training', 'Training Program'), ('study', 'Study Opportunity'), ('exchange', 'Exchange Program'), ('volunteer', 'Volunteer Opportunity'), ('research', 'Research Opportunity'), ('competition', 'Competition'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='remote_worldwide',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='visa_sponsorship',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
