# Generated by Django 5.2.18 on 2026-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0009_alter_opportunity_opportunity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='content_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='normalized_application_url',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
    ]
