# Generated by Django 5.2.18 on 2026-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0010_opportunity_content_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='recommended_action',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='strong_matches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
