# Generated by Django 5.2.18 on 2026-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0011_application_match_override_match_recommended_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='generated_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
