# Generated by Django 5.2.18 on 2026-10-06 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def move_telegram_sources(apps, schema_editor):
    Source = apps.get_model('opportunity_agent', 'Source')
    TelegramSource = apps.get_model('opportunity_agent', 'TelegramSource')
    Opportunity = apps.get_model('opportunity_agent', 'Opportunity')
    alias = schema_editor.connection.alias

    source_ids = list(
        Source.objects.using(alias)
        .filter(source_type='telegram')
        .values_list('pk', flat=True)
    )
    for source_id in source_ids:
        source = Source.objects.using(alias).get(pk=source_id)
        telegram_source = TelegramSource.objects.using(alias).create(
            name=source.name,
            channel_url=source.url,
            country=source.country,
            opportunity_types=source.opportunity_types,
            enabled=source.enabled,
            trust_score=source.trust_score,
            scan_frequency=source.scan_frequency,
            last_scan=source.last_scan,
            last_successful_scan=source.last_successful_scan,
            error_count=source.error_count,
            status=source.status,
            notes=source.notes,
            auto_discovered=source.auto_discovered,
            created_at=source.created_at,
            updated_at=source.updated_at,
        )
        TelegramSource.objects.using(alias).filter(pk=telegram_source.pk).update(
            created_at=source.created_at,
            updated_at=source.updated_at,
        )
        Opportunity.objects.using(alias).filter(source_id=source.pk).update(
            source_id=None,
            telegram_source_id=telegram_source.pk,
        )
        source.delete(using=alias)


def restore_telegram_sources(apps, schema_editor):
    Source = apps.get_model('opportunity_agent', 'Source')
    TelegramSource = apps.get_model('opportunity_agent', 'TelegramSource')
    Opportunity = apps.get_model('opportunity_agent', 'Opportunity')
    alias = schema_editor.connection.alias

    for telegram_source in TelegramSource.objects.using(alias).iterator():
        source = Source.objects.using(alias).create(
            name=telegram_source.name,
            url=telegram_source.channel_url,
            source_type='telegram',
            country=telegram_source.country,
            opportunity_types=telegram_source.opportunity_types,
            enabled=telegram_source.enabled,
            trust_score=telegram_source.trust_score,
            scan_frequency=telegram_source.scan_frequency,
            last_scan=telegram_source.last_scan,
            last_successful_scan=telegram_source.last_successful_scan,
            error_count=telegram_source.error_count,
            status=telegram_source.status,
            notes=telegram_source.notes,
            auto_discovered=telegram_source.auto_discovered,
            created_at=telegram_source.created_at,
            updated_at=telegram_source.updated_at,
        )
        Source.objects.using(alias).filter(pk=source.pk).update(
            created_at=telegram_source.created_at,
            updated_at=telegram_source.updated_at,
        )
        Opportunity.objects.using(alias).filter(
            telegram_source_id=telegram_source.pk,
        ).update(source_id=source.pk, telegram_source_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0012_application_generated_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('website', 'Website'), ('job_site', 'Job Website'), ('scholarship_site', 'Scholarship Website'), ('university', 'University'), ('ngo', 'NGO'), ('government', 'Government'), ('international_org', 'International Organization'), ('company', 'Company Career Page'), ('fellowship_portal', 'Fellowship Portal'), ('grant_portal', 'Grant Portal'), ('rss', 'RSS Feed'), ('api', 'Public API'), ('discovered', 'Discovered Public Source'), ('other', 'Other')], default='website', max_length=40),
        ),
        migrations.AlterField(
            model_name='telegramdestination',
            name='type',
            field=models.CharField(choices=[('destination', 'Destination Group'), ('admin', 'Admin Destination')], default='destination', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_application_limit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='TelegramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_url', models.URLField()),
                ('country', models.CharField(blank=True, max_length=120)),
                ('opportunity_types', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('trust_score', models.FloatField(default=0.0)),
                ('scan_frequency', models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('every_6_hours', 'Every 6 hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=24)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('last_successful_scan', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('scanning', 'Scanning'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('auto_discovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('scan_telegram_sources', 'Can scan Telegram opportunity sources')],
                'indexes': [models.Index(fields=['enabled', 'status'], name='opportunity_enabled_064701_idx'), models.Index(fields=['scan_frequency'], name='opportunity_scan_fr_fbedc5_idx')],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='telegram_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunity_agent.telegramsource'),
        ),
        migrations.RunPython(move_telegram_sources, restore_telegram_sources),
    ]
