# Generated by Django 5.2.18 on 2026-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0013_alter_source_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdestination',
            name='type',
            field=models.CharField(choices=[('applied', 'Applied Applications'), ('rejected', 'Rejected Applications'), ('needs_review', 'Needs Review Applications'), ('system_alert', 'System Alerts'), ('destination', 'Destination Group'), ('admin', 'Admin Destination')], default='destination', max_length=20),
        ),
    ]
