# Generated by Django 5.2.18 on 2026-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0014_alter_telegramdestination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdestination',
            name='type',
            field=models.CharField(choices=[('applied', 'Applied Applications'), ('rejected', 'Rejected Applications'), ('failed', 'Failed Applications'), ('needs_review', 'Needs Review Applications'), ('system_alert', 'System Alerts'), ('destination', 'Destination Group'), ('admin', 'Admin Destination')], default='destination', max_length=20),
        ),
    ]
