# Generated by Django 5.2.18 on 2026-10-06 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0015_alter_telegramdestination_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideradapter',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddIndex(
            model_name='applicationattempt',
            index=models.Index(fields=['application', 'created_at'], name='opportunity_applica_d60285_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__gte', 0), ('match_score__lte', 100)), name='application_match_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='application_attempts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='applicationattempt',
            constraint=models.UniqueConstraint(fields=('application', 'attempt_number'), name='unique_application_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='applicationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='application_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('trust_score__gte', 0), ('trust_score__lte', 1)), name='source_trust_score_0_1'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_ai_match_score__gte', 0), ('minimum_ai_match_score__lte', 100)), name='profile_match_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('daily_application_limit__gte', 1)), name='profile_daily_limit_positive'),
        ),
    ]
