# Generated by Django 5.2.18 on 2026-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0017_aiconversation_aimessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='channel',
            field=models.CharField(choices=[('web', 'Web chat'), ('telegram', 'Telegram')], default='web', max_length=12),
        ),
    ]
