# Generated by Django 6.1.1 on 2026-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0021_application_workflow_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='candidate_scan_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramsource',
            name='last_message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
