# Generated by Django 6.1.1 on 2026-10-08 18:39

from django.db import migrations, models


def populate_application_methods(apps, schema_editor):
    Opportunity = apps.get_model('opportunity_agent', 'Opportunity')
    Opportunity.objects.exclude(application_url='').update(application_method='online')
    Opportunity.objects.filter(application_url='').exclude(
        application_form_url='',
    ).update(application_method='form')


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_agent', '0023_telegrammessageretry'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_method',
            field=models.CharField(choices=[('online', 'Verified online application URL'), ('form', 'Application form URL or file'), ('email', 'Verified application email'), ('telegram', 'Verified Telegram application contact'), ('physical', 'Physical application address'), ('source_only', 'Source page only; application method unverified')], default='source_only', max_length=20),
        ),
        migrations.RunPython(populate_application_methods, migrations.RunPython.noop),
    ]
